# Spring application yaml configuration file.
# Any of these configurations can be overridden using environment variables or system properties.
# See https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html

# Application configurations
spring:
  application:
    name: Greetings App

# Server configuration
server:
  port: 8080

# App metrics and management configuration
# See https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#production-ready-metrics
# for more information.
management:
  metrics:
    export:
      jmx:
        enabled: true
  endpoints:
    enabled-by-default: true

# This should be provided by the environment or looked up in a service registry
services:
  quote:
    url: http://localhost:8181
